apiVersion: v1
kind: Service
metadata:
  name: bitscape-adminer-svc
  labels:
    app: bitscape-db
spec:
  type: NodePort
  selector:
    app: bitscape-adminer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http