apiVersion: v1
kind: Service
metadata:
  name: bitscape-db-svc
  labels:
    app: bitscape-db
spec:
  type: ClusterIP
  selector:
    app: bitscape-db
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres